//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkBookingMaster
    {
        public long TRId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string CreatedById { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileStatus { get; set; }
        public Nullable<short> HotelStatus { get; set; }
    }
}
