//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkBookingDetail
    {
        public long BReqId { get; set; }
        public Nullable<long> TrnId { get; set; }
        public string EmpCode { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string TravelDate { get; set; }
        public string FlightNo { get; set; }
        public string Sector { get; set; }
        public string Purpose { get; set; }
        public string Meal { get; set; }
        public string Beverage { get; set; }
        public string PNR { get; set; }
        public Nullable<short> PNR_Status { get; set; }
        public string BookingType { get; set; }
        public Nullable<bool> IsHotelRequired { get; set; }
        public string HotelCity { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CheckinTime { get; set; }
        public string CheckoutTime { get; set; }
        public Nullable<bool> AirportTransport { get; set; }
        public string AgencyCode { get; set; }
        public bool IsChange { get; set; }
        public int AddNo { get; set; }
        public bool IsBookingcancelled { get; set; }
    }
}
