//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRHRApprovalStatu
    {
        public long appid { get; set; }
        public Nullable<long> ReqId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public string HRName { get; set; }
        public string HREmpCode { get; set; }
    }
}
