//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackParameterMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedBackParameterMaster()
        {
            this.FeedBackEntryDetails = new HashSet<FeedBackEntryDetail>();
        }
    
        public int ID { get; set; }
        public int ParameterId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBackEntryDetail> FeedBackEntryDetails { get; set; }
        public virtual FeedBackGroupMaster FeedBackGroupMaster { get; set; }
        public virtual FeedBackLevelMaster FeedBackLevelMaster { get; set; }
    }
}
