//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackEntryDetail
    {
        public long Id { get; set; }
        public int EntryID { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<short> GroupId { get; set; }
        public Nullable<short> LevelId { get; set; }
    
        public virtual FeedBackEntryMaster FeedBackEntryMaster { get; set; }
        public virtual FeedBackParameterMaster FeedBackParameterMaster { get; set; }
    }
}
