//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInclusionMaster
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string HotelName { get; set; }
        public string Accomodation { get; set; }
        public string Food { get; set; }
        public string AirportTransfers { get; set; }
        public string RoomService { get; set; }
        public string BuffetTime { get; set; }
        public string Laundry { get; set; }
        public string Amenities { get; set; }
        public string WiFi { get; set; }
        public string DrinkingWater { get; set; }
        public string TeaMaker { get; set; }
        public string Newspaper { get; set; }
        public string Discount { get; set; }
        public Nullable<short> EntitlementType { get; set; }
        public string CheckinOutHours { get; set; }
        public string RetentionCancellation { get; set; }
        public string SpouseStay { get; set; }
    }
}
