//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInclusionNonContractualMaster
    {
        public long ID { get; set; }
        public Nullable<long> TravelRequestID { get; set; }
        public string HotelName { get; set; }
        public string Accomodation { get; set; }
        public string Food { get; set; }
        public string AirportTransfers { get; set; }
        public string RoomService { get; set; }
        public string BuffetTime { get; set; }
        public string Laundry { get; set; }
        public Nullable<int> HotelRequestId { get; set; }
    }
}
