//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTermConditionMaster
    {
        public int TCId { get; set; }
        public string TCName { get; set; }
        public short TCGroupId { get; set; }
        public bool IsActive { get; set; }
    }
}
