//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRequestHODFinancialApproval
    {
        public long Id { get; set; }
        public long TravelRequestId { get; set; }
        public string ApproverEmpCodeLevel1 { get; set; }
        public string ApproverEmpCodeLevel2 { get; set; }
        public System.DateTime ApprovalDateLevel1 { get; set; }
        public System.DateTime ApprovalDateLevel2 { get; set; }
        public string ApproverNameLevel1 { get; set; }
        public string ApproverNameLevel2 { get; set; }
        public Nullable<short> ApprovalStatusLevel1 { get; set; }
        public Nullable<short> ApprovalStatusLevel2 { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<int> HotelRequestId { get; set; }
    }
}
