//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITHRequestApproval
    {
        public long Id { get; set; }
        public Nullable<long> TravelRequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string IthName { get; set; }
        public string Phone { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string IthCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string FlightNo { get; set; }
        public string FlightName { get; set; }
        public string DepartureTime { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FlightType { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string FileName { get; set; }
        public string Pnr { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
    }
}
