//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SODEntities : DbContext
    {
        public SODEntities()
            : base("name=SODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BulkBookingDetail> BulkBookingDetails { get; set; }
        public virtual DbSet<BulkBookingMaster> BulkBookingMasters { get; set; }
        public virtual DbSet<CRFinanceUpdateRight> CRFinanceUpdateRights { get; set; }
        public virtual DbSet<CRHRApprovalStatu> CRHRApprovalStatus { get; set; }
        public virtual DbSet<FeedBackEntryDetail> FeedBackEntryDetails { get; set; }
        public virtual DbSet<FeedBackEntryMaster> FeedBackEntryMasters { get; set; }
        public virtual DbSet<FeedBackGroupMaster> FeedBackGroupMasters { get; set; }
        public virtual DbSet<FeedBackLevelMaster> FeedBackLevelMasters { get; set; }
        public virtual DbSet<FeedBackParameterMaster> FeedBackParameterMasters { get; set; }
        public virtual DbSet<HotelInclusionMaster> HotelInclusionMasters { get; set; }
        public virtual DbSet<PassengerMealAllocationDetail> PassengerMealAllocationDetails { get; set; }
        public virtual DbSet<SmsConfirmation> SmsConfirmations { get; set; }
        public virtual DbSet<SmsLog> SmsLogs { get; set; }
        public virtual DbSet<SodAgencyRight> SodAgencyRights { get; set; }
        public virtual DbSet<SODEmployeeChangeRequestMaster> SODEmployeeChangeRequestMasters { get; set; }
        public virtual DbSet<SodHotelListData> SodHotelListDatas { get; set; }
        public virtual DbSet<SodTransportVendorMaster> SodTransportVendorMasters { get; set; }
        public virtual DbSet<SodUserMenu> SodUserMenus { get; set; }
        public virtual DbSet<SodUserProfileDp> SodUserProfileDps { get; set; }
        public virtual DbSet<C__MigrationHistory_Exclude> C__MigrationHistory_Exclude { get; set; }
        public virtual DbSet<BulkBookingRequestApproval> BulkBookingRequestApprovals { get; set; }
        public virtual DbSet<BulkTravelRequestHotelDetail> BulkTravelRequestHotelDetails { get; set; }
        public virtual DbSet<HotelInclusionNonContractualMaster> HotelInclusionNonContractualMasters { get; set; }
        public virtual DbSet<HotelInclusionNonContractualMasterOat> HotelInclusionNonContractualMasterOats { get; set; }
        public virtual DbSet<HotelRequestApproval> HotelRequestApprovals { get; set; }
        public virtual DbSet<HotelRequestApprovalOat> HotelRequestApprovalOats { get; set; }
        public virtual DbSet<HotelRequestCancellation> HotelRequestCancellations { get; set; }
        public virtual DbSet<HotelRequestCancellationByTraveldesk> HotelRequestCancellationByTraveldesks { get; set; }
        public virtual DbSet<HotelRequestCancellationOat> HotelRequestCancellationOats { get; set; }
        public virtual DbSet<HotelRequestHODFinancialApproval> HotelRequestHODFinancialApprovals { get; set; }
        public virtual DbSet<HotelRequestHODFinancialApprovalOat> HotelRequestHODFinancialApprovalOats { get; set; }
        public virtual DbSet<HotelRequestRejection> HotelRequestRejections { get; set; }
        public virtual DbSet<HotelTermConditionGroupMaster> HotelTermConditionGroupMasters { get; set; }
        public virtual DbSet<HotelTermConditionMaster> HotelTermConditionMasters { get; set; }
        public virtual DbSet<HRDepartmentsRight> HRDepartmentsRights { get; set; }
        public virtual DbSet<ITHFinancialApprovalHOD> ITHFinancialApprovalHODs { get; set; }
        public virtual DbSet<ITHRequestApproval> ITHRequestApprovals { get; set; }
        public virtual DbSet<ITHResponseDetail> ITHResponseDetails { get; set; }
        public virtual DbSet<IthVendorListData> IthVendorListDatas { get; set; }
        public virtual DbSet<NonContractualHotelApprovalMaster> NonContractualHotelApprovalMasters { get; set; }
        public virtual DbSet<OALTravelRequestCabDetail> OALTravelRequestCabDetails { get; set; }
        public virtual DbSet<OALTravelRequestFlightDetail> OALTravelRequestFlightDetails { get; set; }
        public virtual DbSet<OALTravelRequestHotelDetail> OALTravelRequestHotelDetails { get; set; }
        public virtual DbSet<OALTravelRequestMaster> OALTravelRequestMasters { get; set; }
        public virtual DbSet<OALTravelRequestPassengerDetail> OALTravelRequestPassengerDetails { get; set; }
        public virtual DbSet<OALUploadItenary> OALUploadItenaries { get; set; }
        public virtual DbSet<OatTravelRequestApproval> OatTravelRequestApprovals { get; set; }
        public virtual DbSet<SodApprover> SodApprovers { get; set; }
        public virtual DbSet<SodApprovers_Old> SodApprovers_Old { get; set; }
        public virtual DbSet<SodApprovers_OnlyStandBy> SodApprovers_OnlyStandBy { get; set; }
        public virtual DbSet<SodBlanketApproval> SodBlanketApprovals { get; set; }
        public virtual DbSet<SodBookingType> SodBookingTypes { get; set; }
        public virtual DbSet<SodCityCodeMaster> SodCityCodeMasters { get; set; }
        public virtual DbSet<SodCXO_Dept_Mapping> SodCXO_Dept_Mapping { get; set; }
        public virtual DbSet<SodCXOLevel> SodCXOLevels { get; set; }
        public virtual DbSet<SODEmployeeChangeRequestDetail> SODEmployeeChangeRequestDetails { get; set; }
        public virtual DbSet<SodEmployeeCommonDetail> SodEmployeeCommonDetails { get; set; }
        public virtual DbSet<SodHotelGSTDetail> SodHotelGSTDetails { get; set; }
        public virtual DbSet<SodHotelPriceListMaster> SodHotelPriceListMasters { get; set; }
        public virtual DbSet<SodLogging> SodLoggings { get; set; }
        public virtual DbSet<SodTravelRequest> SodTravelRequests { get; set; }
        public virtual DbSet<SodTravelRequestApproval> SodTravelRequestApprovals { get; set; }
        public virtual DbSet<SodTravelRequestCabDetail> SodTravelRequestCabDetails { get; set; }
        public virtual DbSet<SodTravelRequestFlightDetail> SodTravelRequestFlightDetails { get; set; }
        public virtual DbSet<SodTravelRequestHotelDetail> SodTravelRequestHotelDetails { get; set; }
        public virtual DbSet<SodTravelRequestMaster> SodTravelRequestMasters { get; set; }
        public virtual DbSet<SodTravelRequestPassengerDetail> SodTravelRequestPassengerDetails { get; set; }
        public virtual DbSet<SodTravelRequestType> SodTravelRequestTypes { get; set; }
        public virtual DbSet<SodUsersInfo> SodUsersInfoes { get; set; }
        public virtual DbSet<TravelRequestModel> TravelRequestModels { get; set; }
        public virtual DbSet<TravelRequestTypeModel> TravelRequestTypeModels { get; set; }
        public virtual DbSet<UserAccountModel> UserAccountModels { get; set; }
        public virtual DbSet<v_SodEmpCommonInfo> v_SodEmpCommonInfo { get; set; }
    
        [DbFunction("SODEntities", "fnSplitString")]
        public virtual IQueryable<fnSplitString_Result> fnSplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplitString_Result>("[SODEntities].[fnSplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<GetSMSCustomerData_Result> GetSMSCustomerData(Nullable<System.DateTime> arrivalDate, string arrivalTime1, string arrivalTime2)
        {
            var arrivalDateParameter = arrivalDate.HasValue ?
                new ObjectParameter("arrivalDate", arrivalDate) :
                new ObjectParameter("arrivalDate", typeof(System.DateTime));
    
            var arrivalTime1Parameter = arrivalTime1 != null ?
                new ObjectParameter("arrivalTime1", arrivalTime1) :
                new ObjectParameter("arrivalTime1", typeof(string));
    
            var arrivalTime2Parameter = arrivalTime2 != null ?
                new ObjectParameter("arrivalTime2", arrivalTime2) :
                new ObjectParameter("arrivalTime2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSMSCustomerData_Result>("GetSMSCustomerData", arrivalDateParameter, arrivalTime1Parameter, arrivalTime2Parameter);
        }
    
        public virtual int SP_BulkBookingApprovalList(string empId, Nullable<int> criteria)
        {
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BulkBookingApprovalList", empIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<SP_BulkBookingHotelList_Result> SP_BulkBookingHotelList(string empId)
        {
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BulkBookingHotelList_Result>("SP_BulkBookingHotelList", empIdParameter);
        }
    
        public virtual ObjectResult<SP_BulkBookingList_Result> SP_BulkBookingList(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string empCode, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BulkBookingList_Result>("SP_BulkBookingList", fromDateParameter, toDateParameter, empCodeParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<SP_BulkBookingListHotelPopup_Result> SP_BulkBookingListHotelPopup(Nullable<int> travelRqstId)
        {
            var travelRqstIdParameter = travelRqstId.HasValue ?
                new ObjectParameter("travelRqstId", travelRqstId) :
                new ObjectParameter("travelRqstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BulkBookingListHotelPopup_Result>("SP_BulkBookingListHotelPopup", travelRqstIdParameter);
        }
    
        public virtual ObjectResult<Sp_BulkBookingUserInfoByTransactionId_Result> Sp_BulkBookingUserInfoByTransactionId(Nullable<int> trId, string empCode, Nullable<int> criteria)
        {
            var trIdParameter = trId.HasValue ?
                new ObjectParameter("TrId", trId) :
                new ObjectParameter("TrId", typeof(int));
    
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BulkBookingUserInfoByTransactionId_Result>("Sp_BulkBookingUserInfoByTransactionId", trIdParameter, empCodeParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<SP_BulkPassengerInfoForHotelRequest_Result> SP_BulkPassengerInfoForHotelRequest(Nullable<int> travelRqstId, Nullable<int> clubid, Nullable<int> criteria)
        {
            var travelRqstIdParameter = travelRqstId.HasValue ?
                new ObjectParameter("travelRqstId", travelRqstId) :
                new ObjectParameter("travelRqstId", typeof(int));
    
            var clubidParameter = clubid.HasValue ?
                new ObjectParameter("clubid", clubid) :
                new ObjectParameter("clubid", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BulkPassengerInfoForHotelRequest_Result>("SP_BulkPassengerInfoForHotelRequest", travelRqstIdParameter, clubidParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<Sp_GetSMSUserData_Result> Sp_GetSMSUserData(Nullable<System.DateTime> arrivalDate, string arrivalTime1, string arrivalTime2)
        {
            var arrivalDateParameter = arrivalDate.HasValue ?
                new ObjectParameter("arrivalDate", arrivalDate) :
                new ObjectParameter("arrivalDate", typeof(System.DateTime));
    
            var arrivalTime1Parameter = arrivalTime1 != null ?
                new ObjectParameter("arrivalTime1", arrivalTime1) :
                new ObjectParameter("arrivalTime1", typeof(string));
    
            var arrivalTime2Parameter = arrivalTime2 != null ?
                new ObjectParameter("arrivalTime2", arrivalTime2) :
                new ObjectParameter("arrivalTime2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetSMSUserData_Result>("Sp_GetSMSUserData", arrivalDateParameter, arrivalTime1Parameter, arrivalTime2Parameter);
        }
    
        public virtual ObjectResult<SP_HotelSimilarAllocation_Result> SP_HotelSimilarAllocation(string hotelname, Nullable<System.DateTime> checkin, string hotelcity)
        {
            var hotelnameParameter = hotelname != null ?
                new ObjectParameter("hotelname", hotelname) :
                new ObjectParameter("hotelname", typeof(string));
    
            var checkinParameter = checkin.HasValue ?
                new ObjectParameter("checkin", checkin) :
                new ObjectParameter("checkin", typeof(System.DateTime));
    
            var hotelcityParameter = hotelcity != null ?
                new ObjectParameter("hotelcity", hotelcity) :
                new ObjectParameter("hotelcity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HotelSimilarAllocation_Result>("SP_HotelSimilarAllocation", hotelnameParameter, checkinParameter, hotelcityParameter);
        }
    
        public virtual ObjectResult<SP_OatApproverBookingList_Result> SP_OatApproverBookingList(Nullable<int> departmentId, Nullable<int> designationId, Nullable<int> empId, Nullable<int> criteria)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OatApproverBookingList_Result>("SP_OatApproverBookingList", departmentIdParameter, designationIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual int Sp_OatDetailInfo(Nullable<int> travelId, Nullable<int> criteria, Nullable<int> empFilter)
        {
            var travelIdParameter = travelId.HasValue ?
                new ObjectParameter("travelId", travelId) :
                new ObjectParameter("travelId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            var empFilterParameter = empFilter.HasValue ?
                new ObjectParameter("empFilter", empFilter) :
                new ObjectParameter("empFilter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_OatDetailInfo", travelIdParameter, criteriaParameter, empFilterParameter);
        }
    
        public virtual int SP_OatITHResponse_byHOD(string idList, Nullable<int> criteria)
        {
            var idListParameter = idList != null ?
                new ObjectParameter("IdList", idList) :
                new ObjectParameter("IdList", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_OatITHResponse_byHOD", idListParameter, criteriaParameter);
        }
    
        public virtual int SP_Sod_GetTravelDesk_HotelDetailCheckTimeConflict()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Sod_GetTravelDesk_HotelDetailCheckTimeConflict");
        }
    
        public virtual ObjectResult<Sp_SodApprover_Result> Sp_SodApprover(Nullable<int> deptId, Nullable<int> criteria)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SodApprover_Result>("Sp_SodApprover", deptIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<Sp_SodBlanketApprovalInfo_Result> Sp_SodBlanketApprovalInfo(Nullable<int> deptId, Nullable<int> criteria)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SodBlanketApprovalInfo_Result>("Sp_SodBlanketApprovalInfo", deptIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodBookingCabStatus(Nullable<int> reqId, Nullable<int> criteria)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodBookingCabStatus", reqIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodBookingHotelStatus(Nullable<int> reqId, Nullable<int> hId, Nullable<int> criteria)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var hIdParameter = hId.HasValue ?
                new ObjectParameter("hId", hId) :
                new ObjectParameter("hId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodBookingHotelStatus", reqIdParameter, hIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingList(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> designationId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingList", fromDateParameter, toDateParameter, departmentIdParameter, designationIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingListCXO(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> designationId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingListCXO", fromDateParameter, toDateParameter, departmentIdParameter, designationIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingListEmpHistory(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingListEmpHistory", fromDateParameter, toDateParameter, departmentIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingListEmpHistory_ByEmployeeCode(string empCode, Nullable<int> criteria)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingListEmpHistory_ByEmployeeCode", empCodeParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingListEmpHistory_Export(string fdate, string tdate, Nullable<int> type, string dept, Nullable<int> criteria)
        {
            var fdateParameter = fdate != null ?
                new ObjectParameter("fdate", fdate) :
                new ObjectParameter("fdate", typeof(string));
    
            var tdateParameter = tdate != null ?
                new ObjectParameter("tdate", tdate) :
                new ObjectParameter("tdate", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingListEmpHistory_Export", fdateParameter, tdateParameter, typeParameter, deptParameter, criteriaParameter);
        }
    
        public virtual int SP_SodBookingListEmpHistory_TravelDesk(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodBookingListEmpHistory_TravelDesk", fromDateParameter, toDateParameter, departmentIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodBookingListEmpStatus(Nullable<int> reqId, Nullable<int> criteria)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodBookingListEmpStatus", reqIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodBookingListEmpStatus_20160804(Nullable<int> reqId, Nullable<int> criteria)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodBookingListEmpStatus_20160804", reqIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodCheckDuplicatePNR(Nullable<int> trRequestID, Nullable<int> criteria)
        {
            var trRequestIDParameter = trRequestID.HasValue ?
                new ObjectParameter("TrRequestID", trRequestID) :
                new ObjectParameter("TrRequestID", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodCheckDuplicatePNR", trRequestIDParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodCheckDuplicatePNR_edit(Nullable<int> trRequestID, Nullable<int> criteria, Nullable<int> addNo)
        {
            var trRequestIDParameter = trRequestID.HasValue ?
                new ObjectParameter("TrRequestID", trRequestID) :
                new ObjectParameter("TrRequestID", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            var addNoParameter = addNo.HasValue ?
                new ObjectParameter("AddNo", addNo) :
                new ObjectParameter("AddNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodCheckDuplicatePNR_edit", trRequestIDParameter, criteriaParameter, addNoParameter);
        }
    
        public virtual ObjectResult<Sp_SodCommon_Result> Sp_SodCommon(Nullable<int> id, Nullable<int> criteria)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SodCommon_Result>("Sp_SodCommon", idParameter, criteriaParameter);
        }
    
        public virtual int Sp_SodCXODeptMapping(string cxoName, Nullable<int> criteria)
        {
            var cxoNameParameter = cxoName != null ?
                new ObjectParameter("cxoName", cxoName) :
                new ObjectParameter("cxoName", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_SodCXODeptMapping", cxoNameParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<Sp_SodEmployeeCommonInfo_Result> Sp_SodEmployeeCommonInfo(Nullable<int> empId, string empName, Nullable<int> criteria, string empFilter)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            var empFilterParameter = empFilter != null ?
                new ObjectParameter("empFilter", empFilter) :
                new ObjectParameter("empFilter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SodEmployeeCommonInfo_Result>("Sp_SodEmployeeCommonInfo", empIdParameter, empNameParameter, criteriaParameter, empFilterParameter);
        }
    
        public virtual ObjectResult<SP_SodGetBillingInfo_Result> SP_SodGetBillingInfo(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<short> type, Nullable<int> criteria, Nullable<long> trId)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(short));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            var trIdParameter = trId.HasValue ?
                new ObjectParameter("TrId", trId) :
                new ObjectParameter("TrId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SodGetBillingInfo_Result>("SP_SodGetBillingInfo", fromdateParameter, todateParameter, typeParameter, criteriaParameter, trIdParameter);
        }
    
        public virtual ObjectResult<string> SP_SodGetEmpAgencyRightInfo(string empCode, Nullable<int> criteria)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("empCode", empCode) :
                new ObjectParameter("empCode", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodGetEmpAgencyRightInfo", empCodeParameter, criteriaParameter);
        }
    
        public virtual int SP_SodGetEmpCodewiseDetails(string empList, Nullable<int> criteria)
        {
            var empListParameter = empList != null ?
                new ObjectParameter("empList", empList) :
                new ObjectParameter("empList", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodGetEmpCodewiseDetails", empListParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SodGetEmpId(string empCode, Nullable<int> criteria)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SodGetEmpId", empCodeParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<string> SP_SodGetHOD(string verticalId, Nullable<int> criteria)
        {
            var verticalIdParameter = verticalId != null ?
                new ObjectParameter("verticalId", verticalId) :
                new ObjectParameter("verticalId", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SodGetHOD", verticalIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodGetHotelApprovalStatus(Nullable<long> trId, Nullable<int> criteria)
        {
            var trIdParameter = trId.HasValue ?
                new ObjectParameter("TrId", trId) :
                new ObjectParameter("TrId", typeof(long));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("criteria", criteria) :
                new ObjectParameter("criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodGetHotelApprovalStatus", trIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodHotelList_TravelDesk(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodHotelList_TravelDesk", fromDateParameter, toDateParameter, departmentIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual int SP_SodHotelList_TravelDesk_DoubleOccupancy(Nullable<long> newTrid, Nullable<long> existingTrid, Nullable<int> hotelid1, Nullable<int> hotelid2)
        {
            var newTridParameter = newTrid.HasValue ?
                new ObjectParameter("newTrid", newTrid) :
                new ObjectParameter("newTrid", typeof(long));
    
            var existingTridParameter = existingTrid.HasValue ?
                new ObjectParameter("existingTrid", existingTrid) :
                new ObjectParameter("existingTrid", typeof(long));
    
            var hotelid1Parameter = hotelid1.HasValue ?
                new ObjectParameter("hotelid1", hotelid1) :
                new ObjectParameter("hotelid1", typeof(int));
    
            var hotelid2Parameter = hotelid2.HasValue ?
                new ObjectParameter("hotelid2", hotelid2) :
                new ObjectParameter("hotelid2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodHotelList_TravelDesk_DoubleOccupancy", newTridParameter, existingTridParameter, hotelid1Parameter, hotelid2Parameter);
        }
    
        public virtual int SP_SodHotelList_TravelDesk_Exceptional(Nullable<int> criteria)
        {
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodHotelList_TravelDesk_Exceptional", criteriaParameter);
        }
    
        public virtual int SP_SodHotelList_TravelDesk1(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> departmentId, Nullable<int> empId, Nullable<int> criteria)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodHotelList_TravelDesk1", fromDateParameter, toDateParameter, departmentIdParameter, empIdParameter, criteriaParameter);
        }
    
        public virtual ObjectResult<SP_SodPassengerInfoForHotelRequest_Result> SP_SodPassengerInfoForHotelRequest(Nullable<long> trid1, Nullable<long> trid2, Nullable<int> hotelid1, Nullable<int> hotelid2, Nullable<int> criteria)
        {
            var trid1Parameter = trid1.HasValue ?
                new ObjectParameter("trid1", trid1) :
                new ObjectParameter("trid1", typeof(long));
    
            var trid2Parameter = trid2.HasValue ?
                new ObjectParameter("trid2", trid2) :
                new ObjectParameter("trid2", typeof(long));
    
            var hotelid1Parameter = hotelid1.HasValue ?
                new ObjectParameter("hotelid1", hotelid1) :
                new ObjectParameter("hotelid1", typeof(int));
    
            var hotelid2Parameter = hotelid2.HasValue ?
                new ObjectParameter("hotelid2", hotelid2) :
                new ObjectParameter("hotelid2", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SodPassengerInfoForHotelRequest_Result>("SP_SodPassengerInfoForHotelRequest", trid1Parameter, trid2Parameter, hotelid1Parameter, hotelid2Parameter, criteriaParameter);
        }
    
        public virtual ObjectResult<SP_SodPassengerInfoForHotelRequestResponsive_Result> SP_SodPassengerInfoForHotelRequestResponsive(Nullable<long> trid1, Nullable<long> trid2, Nullable<int> hotelid1, Nullable<int> hotelid2, Nullable<int> criteria)
        {
            var trid1Parameter = trid1.HasValue ?
                new ObjectParameter("trid1", trid1) :
                new ObjectParameter("trid1", typeof(long));
    
            var trid2Parameter = trid2.HasValue ?
                new ObjectParameter("trid2", trid2) :
                new ObjectParameter("trid2", typeof(long));
    
            var hotelid1Parameter = hotelid1.HasValue ?
                new ObjectParameter("hotelid1", hotelid1) :
                new ObjectParameter("hotelid1", typeof(int));
    
            var hotelid2Parameter = hotelid2.HasValue ?
                new ObjectParameter("hotelid2", hotelid2) :
                new ObjectParameter("hotelid2", typeof(int));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SodPassengerInfoForHotelRequestResponsive_Result>("SP_SodPassengerInfoForHotelRequestResponsive", trid1Parameter, trid2Parameter, hotelid1Parameter, hotelid2Parameter, criteriaParameter);
        }
    
        public virtual int SP_SodValidateEmpCode(string empList, Nullable<int> criteria)
        {
            var empListParameter = empList != null ?
                new ObjectParameter("empList", empList) :
                new ObjectParameter("empList", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodValidateEmpCode", empListParameter, criteriaParameter);
        }
    
        public virtual int SP_SodValidateEmpVerticals(string empList, string verticals, Nullable<int> criteria)
        {
            var empListParameter = empList != null ?
                new ObjectParameter("empList", empList) :
                new ObjectParameter("empList", typeof(string));
    
            var verticalsParameter = verticals != null ?
                new ObjectParameter("Verticals", verticals) :
                new ObjectParameter("Verticals", typeof(string));
    
            var criteriaParameter = criteria.HasValue ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SodValidateEmpVerticals", empListParameter, verticalsParameter, criteriaParameter);
        }
    }
}
