//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonContractualHotelApprovalMaster
    {
        public long Id { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmailId { get; set; }
        public string Status { get; set; }
        public string Designation { get; set; }
    }
}
