//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTravelRequestHotelDetail
    {
        public long Id { get; set; }
        public long TravelRequestId { get; set; }
        public string City { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string CheckinTime { get; set; }
        public string CheckoutTime { get; set; }
        public string Entitlement { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string HotelCode { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress { get; set; }
        public string HotelPhoneNo { get; set; }
        public Nullable<byte> IsAllocated { get; set; }
        public string Remarks_Status { get; set; }
        public string HotelReferenceId { get; set; }
        public Nullable<int> guests { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string HotelType { get; set; }
        public string HotelStatus { get; set; }
        public string HotelConfirmationNo { get; set; }
        public Nullable<bool> AirportTransport { get; set; }
        public string usercancellation { get; set; }
        public Nullable<byte> IsCancelled { get; set; }
        public Nullable<int> clubId { get; set; }
        public string HodApprovalStatus { get; set; }
        public decimal HotelPrice { get; set; }
        public string CheckinTimeHotel { get; set; }
        public string CheckoutTimeHotel { get; set; }
        public bool UserCheckinCheckoutUpdate { get; set; }
        public Nullable<int> HotelRequestId { get; set; }
        public string Occupancy { get; set; }
    }
}
