//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTravelRequestFlightDetail
    {
        public long Id { get; set; }
        public long TravelRequestId { get; set; }
        public string OriginPlace { get; set; }
        public string DestinationPlace { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string DepFlightInfo { get; set; }
        public string DepFlightNumber { get; set; }
        public string DepReason { get; set; }
    }
}
