//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALUploadItenary
    {
        public long Id { get; set; }
        public Nullable<long> TravelRequestId { get; set; }
        public string Pnr { get; set; }
        public string FlightInfo { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string FileName { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
