//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerMealAllocationDetail
    {
        public long Id { get; set; }
        public long TravelRequestId { get; set; }
        public long PassengerId { get; set; }
        public string Sector { get; set; }
        public string MealType { get; set; }
    }
}
