//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodApprover
    {
        public short SodApproverId { get; set; }
        public int DesignationId { get; set; }
        public int DepartmentId { get; set; }
        public int EmployeeId { get; set; }
        public short IsActive { get; set; }
        public string VerticleId { get; set; }
        public string EmailId { get; set; }
    }
}
