//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodAgencyRight
    {
        public int AgencyID { get; set; }
        public string AgencyCode { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
