//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodCXO_Dept_Mapping
    {
        public int Id { get; set; }
        public string CXOName { get; set; }
        public Nullable<int> AllocatedDeptId { get; set; }
        public Nullable<short> IsActive { get; set; }
    }
}
