//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODEmployeeChangeRequestDetail
    {
        public long ID { get; set; }
        public long ReqId { get; set; }
        public int RequestTypeId { get; set; }
        public string RequestTypeName { get; set; }
        public string CRUpdatet1 { get; set; }
        public string CRUpdatet2 { get; set; }
        public string CRUpdatet3 { get; set; }
        public string UserRemarks { get; set; }
        public Nullable<bool> HRApprovalStatus { get; set; }
        public string HRApprovalRemarks { get; set; }
        public Nullable<bool> FinanceStatus { get; set; }
        public string FinanceApprovalRemarks { get; set; }
    }
}
