//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODEmployeeChangeRequestMaster
    {
        public long ReqId { get; set; }
        public string RequestedEmpId { get; set; }
        public string RequestedEmpName { get; set; }
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<System.DateTime> RequestStatusCloseDate { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string DepartmentName { get; set; }
    }
}
