//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodHotelGSTDetail
    {
        public long ID { get; set; }
        public string CityCode { get; set; }
        public string State { get; set; }
        public string PlaceOfBusiness { get; set; }
        public string GSTIN { get; set; }
        public string ARNNo { get; set; }
    }
}
