//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodLogging
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogMessage { get; set; }
        public string LogData { get; set; }
        public string LogSource { get; set; }
        public string HelpLink { get; set; }
        public string HResult { get; set; }
        public string InnerException { get; set; }
        public string MethodName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> EmpId { get; set; }
    }
}
