//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodTravelRequest
    {
        public long TravelRequestId { get; set; }
        public int TravelRequestTypeId { get; set; }
        public string OriginPlace { get; set; }
        public string DestinationPlace { get; set; }
        public System.DateTime TravelDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Passengers { get; set; }
        public System.DateTime RequestDate { get; set; }
        public short SodBookingTypeId { get; set; }
        public string BookingFor { get; set; }
        public short Meals { get; set; }
        public string ReasonForTravel { get; set; }
        public int RequestedEmpId { get; set; }
        public string RequestedEmpName { get; set; }
        public string RequestedEmpDesignation { get; set; }
        public string RequestedEmpDept { get; set; }
        public string TravelerName { get; set; }
        public string TravelerEmailId { get; set; }
        public string TravelerGender { get; set; }
        public string TravelerPhno { get; set; }
        public string Sector { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> ApprovedByEmpId { get; set; }
        public Nullable<int> ApprpvalStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
