//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodTransportVendorMaster
    {
        public int VendorID { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Vendor_Address { get; set; }
        public string CIN { get; set; }
        public string PAN { get; set; }
        public string TIN { get; set; }
        public string Service_Tax_No { get; set; }
        public string PhNo { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string StateCode { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
