//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodTravelRequestCabDetail
    {
        public long ID { get; set; }
        public Nullable<long> TravelRequestID { get; set; }
        public string OneWay_From { get; set; }
        public string OneWay_From_Time { get; set; }
        public string OneWay_To { get; set; }
        public string OneWay_To_Time { get; set; }
        public string Return_From { get; set; }
        public string Return_From_Time { get; set; }
        public string Return_To { get; set; }
        public string Return_To_Time { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<byte> IsAllocated { get; set; }
        public string Remarks_Status { get; set; }
        public string CabReferenceId { get; set; }
    }
}
