//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodUserMenu
    {
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuName { get; set; }
        public string MenuType { get; set; }
        public string MenuPath { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
