//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SodUserProfileDp
    {
        public long dpid { get; set; }
        public string ImageName { get; set; }
        public byte[] DpImage { get; set; }
        public string EmployeeCode { get; set; }
    }
}
