//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequestModel
    {
        public int TravelRequestId { get; set; }
        public int TravelRequestTypeId { get; set; }
        public string OriginPlace { get; set; }
        public string DestinationPlace { get; set; }
        public string Passengers { get; set; }
        public string RequestedUser { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public System.DateTime RequestDate { get; set; }
    }
}
